### ISSUE TITLE
Feature Request: Text Wrapping

### ISSUE THREAD

**Issue by bogdankharchenko** [cloudfour/simple-svg-placeholder#67]
I was curious if it would be possible to add a text wrapping feature -- similar to this

https://codepen.io/maxzz/pen/NzBGVE

**Comment by tylersticka** [comment]
It might be! `foreignObject` should be supported in `img` elements in everything but IE as long as it doesn't reference any external resources and as long as its elements include a `xmlns="http://www.w3.org/1999/xhtml"` attribute. If this actually worked, we'd probably want to make it optional since it will break IE compatibility and will roughly double the size of the asset.

Just to make sure I have full context, can you give an example of the sort of non-wrapping text that inspired this question?

**Comment by bogdankharchenko** [comment]
@tylersticka https://jsfiddle.net/spvubqrm/

**Comment by tylersticka** [comment]
The good news is that this seems to work fine in non-IE browsers!

The bad news is that it increases the size of the function and its output by about a third. So I'd like to think about maybe restructuring the package a bit so modules and tree-shaking can happen intelligently if someone doesn't use that feature. Or maybe split things into two different functions.

@bogdankharchenko If you have an urgent need for this feature, I've pushed my quick and dirty test of the idea to this branch: https://github.com/cloudfour/simple-svg-placeholder/tree/feature/text-wrap

You must set the `textWrap` option to `true` to opt into that type of placeholder.

**Comment by bogdankharchenko** [comment]
@tylersticka first off - you the bomb for the quick turn around

So my initial use case was related to an issue posted on a project which depends on your package.

https://github.com/Cherry/placeholders.dev

See issue https://github.com/Cherry/placeholders.dev/issues/7

I'm going to pull this down a play a bit tomorrow!

**Comment by tylersticka** [comment]
I've decided not to add this feature because it's an uncommon request and bulks up the source code, which feels a bit at odds with the "simple" goal of this library. It also means the resulting SVGs may not function as expected outside of the browser.

If someone wants to fork this repo and maintain their own `multiline-svg-placeholder` or `simple-svg-placeholder-multiline` library, they're welcome to ([see license terms](https://github.com/cloudfour/simple-svg-placeholder/blob/main/LICENSE)).
